name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install flake8 html-testRunner
      
      - name: Lint with flake8
        run: flake8 src
      
      - name: Create test data directory if needed
        run: |
          mkdir -p tests/test_data/raw
          mkdir -p tests/test_data/processed
          # If test_transactions.csv doesn't exist, create a sample one
          if [ ! -f tests/test_data/raw/test_transactions.csv ]; then
            echo "date,description,amount,category,account" > tests/test_data/raw/test_transactions.csv
            echo "2023-01-01,Grocery Store,-50.25,Food,Credit Card" >> tests/test_data/raw/test_transactions.csv
            echo "2023-01-02,Gas Station,-35.00,Transportation,Credit Card" >> tests/test_data/raw/test_transactions.csv
            echo "2023-01-03,Salary,2000.00,Income,Checking" >> tests/test_data/raw/test_transactions.csv
          fi
      
      - name: Run tests
        run: python -m tests.run_tests
        env:
          DEFAULT_LLM_PROVIDER: huggingface
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY || 'dummy_key_for_ci' }}
          DATA_DIR: tests/test_data
      
      - name: Validate code structure
        run: |
          echo "Validating project structure..."
          test -d src/api || { echo "Missing src/api directory"; exit 1; }
          test -d src/data_processing || { echo "Missing src/data_processing directory"; exit 1; }
          test -d src/embedding || { echo "Missing src/embedding directory"; exit 1; }
          test -d src/rag || { echo "Missing src/rag directory"; exit 1; }
          echo "Project structure validated successfully" 