name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install flake8 html-testRunner
      
      - name: Lint with flake8
        run: flake8 src
      
      - name: Run tests
        run: python -m tests.run_tests
        env:
          DEFAULT_LLM_PROVIDER: huggingface
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
          DATA_DIR: tests/test_data
      
      - name: Validate code structure
        run: |
          echo "Validating project structure..."
          test -d src/api || { echo "Missing src/api directory"; exit 1; }
          test -d src/data_processing || { echo "Missing src/data_processing directory"; exit 1; }
          test -d src/embedding || { echo "Missing src/embedding directory"; exit 1; }
          test -d src/rag || { echo "Missing src/rag directory"; exit 1; }
          echo "Project structure validated successfully" 